# Compiler Configuration
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
# Project Configuration
project.name=AndroidMCP
project.android.compileSdk=37
project.android.minSdk=27
project.android.targetSdk=37
project.app.packageName=com.wzvideni.androidmcp
project.app.versionName="1.0.0"
project.app.versionCode=1